export const SAMPLE_USERS = [
  {
    _id: '5dfa47351f3b5d5f064de719',
    index: 0,
    guid: '9df78ad8-d422-48ce-af74-0e31c08e07bf',
    isActive: false,
    balance: '$2,069.95',
    picture: 'http://placehold.it/32x32',
    age: 23,
    eyeColor: 'green',
    name: 'Lana Booker',
    gender: 'female',
    company: 'ECLIPSENT',
    email: 'lanabooker@eclipsent.com',
    phone: '+1 (955) 566-2171',
    address: '902 Imlay Street, Cashtown, Ohio, 1729',
    about:
      'Id ipsum veniam duis elit. Duis ea non ad proident. Ea non aliquip fugiat id do aute ea laboris ullamco. Exercitation velit occaecat anim dolore quis. Ad anim ex magna proident. In labore amet aliquip sint. Magna ut mollit minim aute ea sunt minim.\r\n',
    registered: '2017-01-02T05:36:52 +05:00',
    latitude: -55.692165,
    longitude: -34.543945,
    tags: ['do', 'labore', 'mollit', 'labore', 'reprehenderit', 'Lorem', 'est'],
    friends: [
      {
        id: 0,
        name: 'Hughes Cooper',
      },
      {
        id: 1,
        name: 'Anna Snider',
      },
      {
        id: 2,
        name: 'Dickerson Mcintyre',
      },
    ],
    greeting: 'Hello, Lana Booker! You have 1 unread messages.',
    favoriteFruit: 'banana',
  },
  {
    _id: '5dfa4735e02299a005ba232d',
    index: 1,
    guid: '0b791838-36b0-4070-b6b2-d7e04101a6b1',
    isActive: true,
    balance: '$3,127.67',
    picture: 'http://placehold.it/32x32',
    age: 25,
    eyeColor: 'blue',
    name: 'Lilly Boyd',
    gender: 'female',
    company: 'REALMO',
    email: 'lillyboyd@realmo.com',
    phone: '+1 (839) 518-2006',
    address: '556 Arlington Place, Fannett, Vermont, 870',
    about:
      'Minim ea nulla ea aute. Id sint sit qui et reprehenderit proident quis. Ipsum et anim fugiat voluptate aliqua ea occaecat aliqua reprehenderit sunt ullamco voluptate Lorem minim. Aliquip Lorem consectetur est voluptate labore voluptate amet consectetur exercitation ea ad laborum. Veniam magna cillum reprehenderit consequat deserunt deserunt.\r\n',
    registered: '2016-05-16T03:25:36 +04:00',
    latitude: -56.60406,
    longitude: -24.822489,
    tags: [
      'ex',
      'officia',
      'officia',
      'reprehenderit',
      'veniam',
      'veniam',
      'officia',
    ],
    friends: [
      {
        id: 0,
        name: 'Cora Warren',
      },
      {
        id: 1,
        name: 'Elvira Clemons',
      },
      {
        id: 2,
        name: 'Kirkland Lowery',
      },
    ],
    greeting: 'Hello, Lilly Boyd! You have 6 unread messages.',
    favoriteFruit: 'apple',
  },
  {
    _id: '5dfa4735c7299f13ffa8e5c1',
    index: 2,
    guid: '46814737-2cf3-4c42-afa9-deeccfdeb539',
    isActive: true,
    balance: '$2,579.66',
    picture: 'http://placehold.it/32x32',
    age: 21,
    eyeColor: 'brown',
    name: 'Sherry Oneil',
    gender: 'female',
    company: 'FROSNEX',
    email: 'sherryoneil@frosnex.com',
    phone: '+1 (826) 565-3197',
    address: '267 Stillwell Place, Blairstown, Nevada, 584',
    about:
      'Id officia ad amet minim irure. Sit eiusmod aute irure pariatur dolor veniam aliquip sit. Duis eu tempor excepteur veniam tempor ut sunt nulla et. Aliquip cupidatat aliqua amet anim fugiat esse non elit voluptate. Sunt reprehenderit in tempor nostrud commodo est nostrud minim proident officia. Aliqua ex fugiat culpa ad ad commodo pariatur non ad ea ea.\r\n',
    registered: '2018-08-20T12:09:15 +04:00',
    latitude: -31.726037,
    longitude: -92.877079,
    tags: ['elit', 'ea', 'voluptate', 'et', 'commodo', 'laboris', 'in'],
    friends: [
      {
        id: 0,
        name: 'Bruce Conrad',
      },
      {
        id: 1,
        name: 'Natasha Rush',
      },
      {
        id: 2,
        name: 'Delores Mayer',
      },
    ],
    greeting: 'Hello, Sherry Oneil! You have 6 unread messages.',
    favoriteFruit: 'apple',
  },
  {
    _id: '5dfa47351c83583a0378cb1b',
    index: 3,
    guid: 'd6d309bf-cccb-420e-8b7c-86ab93d93fcc',
    isActive: false,
    balance: '$1,351.77',
    picture: 'http://placehold.it/32x32',
    age: 32,
    eyeColor: 'brown',
    name: 'Claudia Lane',
    gender: 'female',
    company: 'VERBUS',
    email: 'claudialane@verbus.com',
    phone: '+1 (942) 484-3869',
    address: '529 Hastings Street, Dundee, Marshall Islands, 9962',
    about:
      'Reprehenderit ipsum laborum Lorem eiusmod enim nisi. Aliquip cillum eu dolore et reprehenderit ullamco labore eiusmod deserunt et ullamco tempor minim. Lorem commodo proident eu pariatur laboris excepteur dolor consectetur mollit.\r\n',
    registered: '2014-02-06T06:15:57 +05:00',
    latitude: 45.525809,
    longitude: 142.049517,
    tags: ['sint', 'laborum', 'qui', 'ipsum', 'adipisicing', 'eu', 'enim'],
    friends: [
      {
        id: 0,
        name: 'Bobbie Justice',
      },
      {
        id: 1,
        name: 'Sabrina Pitts',
      },
      {
        id: 2,
        name: 'Chambers Gregory',
      },
    ],
    greeting: 'Hello, Claudia Lane! You have 7 unread messages.',
    favoriteFruit: 'banana',
  },
  {
    _id: '5dfa4735e32fcc0605781c93',
    index: 4,
    guid: '754a066f-e3de-41b4-b0a9-e36b37f4c3eb',
    isActive: false,
    balance: '$2,699.68',
    picture: 'http://placehold.it/32x32',
    age: 24,
    eyeColor: 'green',
    name: 'Ochoa Skinner',
    gender: 'male',
    company: 'SIGNIDYNE',
    email: 'ochoaskinner@signidyne.com',
    phone: '+1 (852) 451-2192',
    address: '298 Jackson Street, Draper, American Samoa, 8187',
    about:
      'Culpa aliquip dolore et ex anim amet aliqua incididunt est pariatur nostrud aliqua commodo. Aliqua cillum pariatur ea cillum sint tempor tempor labore nisi deserunt est enim proident. Ea culpa cupidatat ullamco occaecat excepteur ipsum nulla sit consequat. Veniam mollit incididunt aliquip cillum deserunt. Ad nisi laboris excepteur sit nisi. Magna duis veniam ipsum minim velit ad. Aliquip nostrud culpa ad qui amet sint dolore nisi.\r\n',
    registered: '2019-10-30T01:37:41 +04:00',
    latitude: 66.277421,
    longitude: -79.473539,
    tags: ['deserunt', 'ea', 'magna', 'mollit', 'enim', 'adipisicing', 'nisi'],
    friends: [
      {
        id: 0,
        name: 'Gross Wall',
      },
      {
        id: 1,
        name: 'Mara Cobb',
      },
      {
        id: 2,
        name: 'Krystal Dominguez',
      },
    ],
    greeting: 'Hello, Ochoa Skinner! You have 6 unread messages.',
    favoriteFruit: 'strawberry',
  },
  {
    _id: '5dfa4735ab5fa72a394a7680',
    index: 5,
    guid: 'b09fecec-095f-43b3-b484-522d67088cca',
    isActive: true,
    balance: '$3,988.23',
    picture: 'http://placehold.it/32x32',
    age: 39,
    eyeColor: 'green',
    name: 'Gallagher Barr',
    gender: 'male',
    company: 'BEDDER',
    email: 'gallagherbarr@bedder.com',
    phone: '+1 (909) 590-2970',
    address: '540 Seaview Court, Rossmore, Oregon, 290',
    about:
      'Quis ullamco ullamco quis qui occaecat nisi reprehenderit adipisicing et labore fugiat velit. Magna ut mollit deserunt reprehenderit laborum velit est. Amet labore proident anim ex sit minim eiusmod ea commodo elit. Cillum deserunt commodo nulla nulla aliquip aute eiusmod tempor esse nisi adipisicing. Ipsum mollit officia mollit amet ex sunt nulla nostrud aliqua qui Lorem.\r\n',
    registered: '2018-07-16T02:13:28 +04:00',
    latitude: 65.095721,
    longitude: -98.073063,
    tags: [
      'ut',
      'nisi',
      'commodo',
      'exercitation',
      'nostrud',
      'cupidatat',
      'laborum',
    ],
    friends: [
      {
        id: 0,
        name: 'Corrine Ewing',
      },
      {
        id: 1,
        name: 'Roy Robles',
      },
      {
        id: 2,
        name: 'Ramos Patton',
      },
    ],
    greeting: 'Hello, Gallagher Barr! You have 10 unread messages.',
    favoriteFruit: 'strawberry',
  },
  {
    _id: '5dfa47350a603f40c9c310bf',
    index: 6,
    guid: '5b3b52b2-5c20-402c-98de-8c5ca75e67af',
    isActive: true,
    balance: '$2,478.78',
    picture: 'http://placehold.it/32x32',
    age: 36,
    eyeColor: 'blue',
    name: 'Pruitt Cain',
    gender: 'male',
    company: 'COMTRACT',
    email: 'pruittcain@comtract.com',
    phone: '+1 (886) 445-2063',
    address: '496 Conklin Avenue, Websterville, Maine, 5689',
    about:
      'Sint tempor occaecat nulla officia est reprehenderit elit id sit nulla reprehenderit amet. Consectetur fugiat anim voluptate ea aute eu veniam ea ex officia ex. Commodo minim ut cupidatat nostrud nulla sit esse commodo qui amet. Reprehenderit elit sint voluptate nulla sit deserunt. Sit officia cillum qui ea consequat enim cillum exercitation dolore ipsum. Laboris ex labore ut irure culpa. Id cillum id Lorem id esse non ut eu irure proident.\r\n',
    registered: '2014-08-13T04:43:40 +04:00',
    latitude: -46.266147,
    longitude: -145.136857,
    tags: ['laboris', 'irure', 'est', 'esse', 'dolor', 'ullamco', 'mollit'],
    friends: [
      {
        id: 0,
        name: 'Susanna Delgado',
      },
      {
        id: 1,
        name: 'Inez Jarvis',
      },
      {
        id: 2,
        name: 'Evangeline Molina',
      },
    ],
    greeting: 'Hello, Pruitt Cain! You have 6 unread messages.',
    favoriteFruit: 'banana',
  },
];
